provider "aws" {
  version = "1.56.0"
  region  = "ap-southeast-1"
}

module "athauth" {
  source                                  = "../../"
  environment                             = "staging"
  lambda_code_bucket                      = "tools-infra-lambda-bucket"
  log_retention_days                      = "7"
  get_all_group_lambda_code_path          = "getAllGroups.zip"
  save_group_lambda_code_path             = "createGroup.zip"
  update_group_lambda_code_path           = "updateGroup.zip"
  delete_group_lambda_code_path           = "deleteGroup.zip"
  get_group_by_id_lambda_code_path        = "getGroupById.zip"
  get_group_members_lambda_code_path      = "getGroupMembership.zip"
  delete_group_members_lambda_code_path   = "deleteUserFromGroup.zip"
  add_group_members_lambda_code_path      = "addUserToGroup.zip"
  get_group_permissions_lambda_code_path        = "getGroupRole.zip"
  delete_group_permissions_lambda_code_path     = "deleteRoleFromGroup.zip"
  add_group_permissions_lambda_code_path        = "addRoleToGroup.zip"
  get_group_by_name_lambda_code_path      = "getGroupByName.zip"
  get_all_ops_groups_lambda_code_path     = "getAllOpsGroups.zip"
  update_ops_members_lambda_code_path     = "addOpsUserToGroups.zip"
  get_all_permissions_lambda_code_path    = "getAllPermissions.zip"
  save_permission_lambda_code_path        = "createPermission.zip"
  get_permission_by_name_lambda_code_path = "getPermissionByName.zip"
  get_permission_by_id_lambda_code_path   = "getPermissionById.zip"
  update_permission_lambda_code_path      = "updatePermission.zip"
  delete_permission_lambda_code_path      = "deletePermission.zip"
  get_all_roles_lambda_code_path          = "getAllRoles.zip"
  save_role_lambda_code_path              = "createRole.zip"
  get_role_by_name_lambda_code_path       = "getRoleByName.zip"
  get_role_by_id_lambda_code_path         = "getRoleById.zip"
  update_role_lambda_code_path            = "updateRole.zip"
  delete_role_lambda_code_path            = "deleteRole.zip"
  get_all_users_lambda_code_path          = "getAllUsers.zip"
  save_user_lambda_code_path              = "createUser.zip"
  get_user_by_email_lambda_code_path      = "getUserByEmail.zip"
  change_user_password_lambda_code_path   = "changePassword.zip"
  get_refresh_tokens_lambda_code_path     = "getRefreshTokens.zip"
  revoke_refresh_tokens_lambda_code_path  = "revokeRefreshTokens.zip"
  unblock_user_lambda_code_path           = "unblockUser.zip"
  get_user_by_username_lambda_code_path   = "getUserByUsername.zip"
  update_username_lambda_code_path        = "updateUsername.zip"
  get_user_by_id_lambda_code_path         = "getUserById.zip"
  delete_user_lambda_code_path            = "deleteUser.zip"
  update_user_lambda_code_path            = "updateUser.zip"
  get_user_groups_lambda_code_path        = "getUserGroups.zip"
  add_user_to_groups_lambda_code_path     = "addUserToManyGroups.zip"
  authoriser_lambda_code_path             = "authoriser.zip"

  auth0_domain = "tvlk-dev.auth0.com"

  auth0_client_id = "NziCJQCIaiVNIqDa6p7VDyekAzDls34u"

  extension_api_url = "https://tvlk-dev.us8.webtask.io/adf6e2f2b84784b57522e3b19dfc9201/api"

  auth0_mgmt_api_url = "https://tvlk-dev.auth0.com/api/v2"
}
